language: node_js
node_js:
  - 12
before_install:
  - npm install

jobs:
  include:
    - stage: Unit tests and produce coverage
      name: Unit tests
      node_js: node
      script: jest --coverage
    - script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      name: Produce coverage
    - script: rm -rf ./coverage
      name: Remove coverage
