language: node_js
node_js:
  - 12
before_install:
  - npm install

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage
      script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      script: rm -rf ./coverage
